// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljlbsqcnkyazznmldlyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqbGJzcWNua3lhenpubWxkbHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjkzNzgsImV4cCI6MjA1ODg0NTM3OH0.QcreSc9yPbZfDNJM5yFiUBeMfNlIuipxXTwVNufA3wA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);